### ISSUE TITLE
Installing the software

### ISSUE THREAD

**Issue by Aggon98** [nilsberglund-orleans/YouTube-simulations#6]
Dear creator,
I'm thrilled to find your software as I'm fascinated by the butterfly effect.
Now I happen to have little to no experience with IT and I'm new to github.
I have no idea how to install software from github as I can't find any .exe file.
Could you please help me out because I'd love to see your simulator
At the same time I'll also learn something new about Github ^^

Many thanks in advance!
Joris

**Comment by nilsberglund-orleans** [comment]
Sorry, but you will have to compile the code yourself, since this depends a lot on the OS you are using. 
On Unix-flavoured systems, such as Linux and MacOS, there is no need to install a compiler, you just have to follow the instructions in the README.md file. On Windows, you may have to install gcc or a comparable compiler first.
There must be many tutorials on how to do that online, or you can seek help on stackoverflow.
